// Inline the cached font subsets (latin + Persian) as base64 @font-face rules so the single-file build
// works offline. Source: fonts/fonts.json + fonts/*.woff2 (Google Fonts, SIL OFL 1.1).
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
const faces = JSON.parse(readFileSync('fonts/fonts.json', 'utf8'));
let total = 0;
const css = faces.map(f => {
  const data = readFileSync(`fonts/${f.file}`); total += data.length;
  return `@font-face{font-family:'${f.family}';font-style:normal;font-weight:${f.weight};font-display:swap;` +
    `src:url(data:font/woff2;base64,${data.toString('base64')}) format('woff2');unicode-range:${f.range};}`;
}).join('\n');
mkdirSync('src/generated', { recursive: true });
writeFileSync('src/generated/fonts.css', `/* generated by tools/fonts.mjs, do not edit */\n${css}\n`);
console.log(`fonts: ${faces.length} faces, ${Math.round(total / 1024)} KB`);
